--- TO SSELECT A ROW OF TABLE---
SELECT * FROM MealsInfo;

-----LIMIT ROWS FROM TABLE--- 
SELECT* FROM MealInfo limit 1;

-----LIMIT ROWS FROM TABLE---
SELECT  * FROM VALUES limit 5

----DELETE-----
DELETE from VALUES
SELECT * FROM VALUES WHERE meal_id=1438


UPDATE VALUES
SET category = "Salad" WHERE meal_id=2307;
SELECT* FROM VALUES;


INSERT into VALUES values(1755,"Bevarages","Thai");
SELECT * FROM VALUES

-----DROP TABLE-----
INSERT into VALUES values(2640,"Straters","Thai");
SELECT *FROM VALUES;

-----SORT IN ORDER----
SELECT * FROM VALUES ORDER BY Pizza DESC;
